handle empty response
Idein/gatekeeper pull request #65
Opened 2023-04-28 08:03 UTC by garasubo

When the server sends RST packet without any contents, the incoming
thread will be shutdown with IO error. But outbound thread keeps alive
because it doesn't recognize incoming thread termination.

In this commit, I added channels to notify incoming thread termination
to outbound thread and outbound thread termination to incoming thread.

2023-04-28 12:01 UTC, legokichi commented on src/relay.rs
> -    server_addr: SocketAddr,
unused fields

2023-05-01 05:52 UTC, garasubo commented on src/relay.rs
> +                match another_rx.try_recv() {
Sounds a good idea. Fixed

2023-05-01 10:00 UTC, eldesh requested changes
The shutdown_relay_by_connection_rest passes on the master branch before the merge.
It seems that the fixes are not being tested properly.

2023-05-02 01:05 UTC, garasubo commented
@eldesh It seems all tests passed in this branch as well.
https://app.circleci.com/pipelines/github/Idein/gatekeeper/205/workflows/57a113cb-79b7-4022-a4ad-15831adae9d1
Is there any tests not running in this CI?

2023-05-02 06:28 UTC, legokichi submitted a review, later dismissed
dante-server seems to pass RSTs transparently.
However, I think this PR is fine as long as the connection can be simply disconnected

2023-05-02 07:39 UTC, eldesh commented
> It seems all tests passed in this branch as well.

Yes I see. It has passed all test cases.

But doesn't this PR fix bugs in the previous version?
If so, then the newly added test (`shutdown_relay_by_connection_rest`) should fail in the **master branch** (i.e, in the pre-fixed version), right?

2023-05-02 09:44 UTC, garasubo commented
I see. Added Node.js based test. I firstly tried to add unit test in Rust, but it is a little bit difficult since there is no straight way to close TCP session with RST packet using std. So, I added a snippet, which was used to find this bug.

2023-05-02 10:38 UTC, eldesh commented on example.yml
> +- Allow:
Is this change as intended?

2023-05-02 10:44 UTC, eldesh submitted a review, later dismissed
I have confirmed that the test fails in previous versions.
Looks good :+1:

2023-05-08 02:54 UTC, garasubo commented on example.yml
> +- Allow:
No, removed

2023-05-08 03:06 UTC, legokichi approved these changes

2023-05-08 03:09 UTC, merged